import { MigrationInterface, QueryRunner } from "typeorm";

export class SyncSchemaWithEntities1785617400031 implements MigrationInterface {
    name = 'SyncSchemaWithEntities1785617400031'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_calendars_owner_id"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendars" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(60) NOT NULL, "color" varchar(20), "owner_id" integer NOT NULL, "is_personal" boolean NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "temporary_calendars"("id", "name", "color", "owner_id", "is_personal", "created_at", "updated_at") SELECT "id", "name", "color", "owner_id", "is_personal", "created_at", "updated_at" FROM "calendars"`);
        await queryRunner.query(`DROP TABLE "calendars"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendars" RENAME TO "calendars"`);
        await queryRunner.query(`CREATE INDEX "IDX_calendars_owner_id" ON "calendars" ("owner_id") `);
        await queryRunner.query(`DROP INDEX "IDX_calendar_members_user_id"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendar_members" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_id" integer NOT NULL, "user_id" integer NOT NULL, "role" varchar(10) NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_calendar_members_calendar_user" UNIQUE ("calendar_id", "user_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_calendar_members"("id", "calendar_id", "user_id", "role", "created_at") SELECT "id", "calendar_id", "user_id", "role", "created_at" FROM "calendar_members"`);
        await queryRunner.query(`DROP TABLE "calendar_members"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendar_members" RENAME TO "calendar_members"`);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_members_user_id" ON "calendar_members" ("user_id") `);
        await queryRunner.query(`DROP INDEX "UQ_calendar_invitations_pending"`);
        await queryRunner.query(`DROP INDEX "IDX_calendar_invitations_invitee_id"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendar_invitations" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_id" integer NOT NULL, "inviter_id" integer NOT NULL, "invitee_id" integer NOT NULL, "status" varchar(10) NOT NULL DEFAULT ('pending'), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "responded_at" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_calendar_invitations"("id", "calendar_id", "inviter_id", "invitee_id", "status", "created_at", "responded_at") SELECT "id", "calendar_id", "inviter_id", "invitee_id", "status", "created_at", "responded_at" FROM "calendar_invitations"`);
        await queryRunner.query(`DROP TABLE "calendar_invitations"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendar_invitations" RENAME TO "calendar_invitations"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_calendar_invitations_pending" ON "calendar_invitations" ("calendar_id", "invitee_id") WHERE "status" = 'pending'`);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_invitations_invitee_id" ON "calendar_invitations" ("invitee_id") `);
        await queryRunner.query(`DROP INDEX "IDX_recurrence_exceptions_exception_date"`);
        await queryRunner.query(`DROP INDEX "IDX_recurrence_exceptions_recurring_event_id"`);
        await queryRunner.query(`CREATE TABLE "temporary_recurrence_exceptions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "recurring_event_id" integer NOT NULL, "exception_date" date NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_recurrence_exceptions_recurring_date" UNIQUE ("recurring_event_id", "exception_date"))`);
        await queryRunner.query(`INSERT INTO "temporary_recurrence_exceptions"("id", "recurring_event_id", "exception_date", "created_at") SELECT "id", "recurring_event_id", "exception_date", "created_at" FROM "recurrence_exceptions"`);
        await queryRunner.query(`DROP TABLE "recurrence_exceptions"`);
        await queryRunner.query(`ALTER TABLE "temporary_recurrence_exceptions" RENAME TO "recurrence_exceptions"`);
        await queryRunner.query(`CREATE INDEX "IDX_recurrence_exceptions_exception_date" ON "recurrence_exceptions" ("exception_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_recurrence_exceptions_recurring_event_id" ON "recurrence_exceptions" ("recurring_event_id") `);
        await queryRunner.query(`DROP INDEX "IDX_calendar_events_calendar_id"`);
        await queryRunner.query(`DROP INDEX "IDX_calendar_events_instance_date"`);
        await queryRunner.query(`DROP INDEX "IDX_calendar_events_recurring_event_id"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendar_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "recurring_event_id" integer, "instance_date" date, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "is_modified" boolean DEFAULT (0), "title_override" varchar(255), "description_override" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "calendar_id" integer, "reminders_customized" boolean NOT NULL DEFAULT (0), CONSTRAINT "UQ_calendar_events_recurring_instance" UNIQUE ("recurring_event_id", "instance_date"))`);
        await queryRunner.query(`INSERT INTO "temporary_calendar_events"("id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized") SELECT "id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized" FROM "calendar_events"`);
        await queryRunner.query(`DROP TABLE "calendar_events"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendar_events" RENAME TO "calendar_events"`);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_events_calendar_id" ON "calendar_events" ("calendar_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_events_instance_date" ON "calendar_events" ("instance_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_events_recurring_event_id" ON "calendar_events" ("recurring_event_id") `);
        await queryRunner.query(`DROP INDEX "UQ_event_reminders_event_minutes"`);
        await queryRunner.query(`DROP INDEX "IDX_event_reminders_calendar_event_id"`);
        await queryRunner.query(`CREATE TABLE "temporary_event_reminders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_event_id" integer NOT NULL, "reminder_minutes" integer NOT NULL, "sent_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "temporary_event_reminders"("id", "calendar_event_id", "reminder_minutes", "sent_at", "created_at", "updated_at") SELECT "id", "calendar_event_id", "reminder_minutes", "sent_at", "created_at", "updated_at" FROM "event_reminders"`);
        await queryRunner.query(`DROP TABLE "event_reminders"`);
        await queryRunner.query(`ALTER TABLE "temporary_event_reminders" RENAME TO "event_reminders"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_event_reminders_event_minutes" ON "event_reminders" ("calendar_event_id", "reminder_minutes") `);
        await queryRunner.query(`CREATE INDEX "IDX_event_reminders_calendar_event_id" ON "event_reminders" ("calendar_event_id") `);
        await queryRunner.query(`DROP INDEX "IDX_calendars_owner_id"`);
        await queryRunner.query(`DROP INDEX "IDX_calendar_members_user_id"`);
        await queryRunner.query(`DROP INDEX "UQ_calendar_invitations_pending"`);
        await queryRunner.query(`DROP INDEX "IDX_calendar_invitations_invitee_id"`);
        await queryRunner.query(`DROP INDEX "IDX_recurring_events_calendar_id"`);
        await queryRunner.query(`DROP INDEX "IDX_recurrence_exceptions_exception_date"`);
        await queryRunner.query(`DROP INDEX "IDX_recurrence_exceptions_recurring_event_id"`);
        await queryRunner.query(`DROP INDEX "IDX_calendar_events_calendar_id"`);
        await queryRunner.query(`DROP INDEX "IDX_calendar_events_instance_date"`);
        await queryRunner.query(`DROP INDEX "IDX_calendar_events_recurring_event_id"`);
        await queryRunner.query(`DROP INDEX "UQ_event_reminders_event_minutes"`);
        await queryRunner.query(`DROP INDEX "IDX_event_reminders_calendar_event_id"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendar_members" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_id" integer NOT NULL, "user_id" integer NOT NULL, "role" varchar(10) NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "temporary_calendar_members"("id", "calendar_id", "user_id", "role", "created_at") SELECT "id", "calendar_id", "user_id", "role", "created_at" FROM "calendar_members"`);
        await queryRunner.query(`DROP TABLE "calendar_members"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendar_members" RENAME TO "calendar_members"`);
        await queryRunner.query(`CREATE TABLE "temporary_recurrence_exceptions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "recurring_event_id" integer NOT NULL, "exception_date" date NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "temporary_recurrence_exceptions"("id", "recurring_event_id", "exception_date", "created_at") SELECT "id", "recurring_event_id", "exception_date", "created_at" FROM "recurrence_exceptions"`);
        await queryRunner.query(`DROP TABLE "recurrence_exceptions"`);
        await queryRunner.query(`ALTER TABLE "temporary_recurrence_exceptions" RENAME TO "recurrence_exceptions"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendar_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "recurring_event_id" integer, "instance_date" date, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "is_modified" boolean DEFAULT (0), "title_override" varchar(255), "description_override" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "calendar_id" integer, "reminders_customized" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "temporary_calendar_events"("id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized") SELECT "id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized" FROM "calendar_events"`);
        await queryRunner.query(`DROP TABLE "calendar_events"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendar_events" RENAME TO "calendar_events"`);
        await queryRunner.query(`CREATE TABLE "temporary_recurring_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "recurrence_type" varchar(20) NOT NULL, "recurrence_interval" integer NOT NULL DEFAULT (1), "days_of_week" varchar(20), "day_of_month" integer, "month_of_year" integer, "recurrence_end_date" datetime, "no_end_date" boolean NOT NULL DEFAULT (0), "rrule_string" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "reminder_minutes" integer, "calendar_id" integer)`);
        await queryRunner.query(`INSERT INTO "temporary_recurring_events"("id", "user_id", "title", "description", "color", "start_date", "end_date", "recurrence_type", "recurrence_interval", "days_of_week", "day_of_month", "month_of_year", "recurrence_end_date", "no_end_date", "rrule_string", "created_at", "updated_at", "reminder_minutes", "calendar_id") SELECT "id", "user_id", "title", "description", "color", "start_date", "end_date", "recurrence_type", "recurrence_interval", "days_of_week", "day_of_month", "month_of_year", "recurrence_end_date", "no_end_date", "rrule_string", "created_at", "updated_at", "reminder_minutes", "calendar_id" FROM "recurring_events"`);
        await queryRunner.query(`DROP TABLE "recurring_events"`);
        await queryRunner.query(`ALTER TABLE "temporary_recurring_events" RENAME TO "recurring_events"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendar_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "recurring_event_id" integer, "instance_date" date, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "is_modified" boolean DEFAULT (0), "title_override" varchar(255), "description_override" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "calendar_id" integer, "reminders_customized" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "temporary_calendar_events"("id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized") SELECT "id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized" FROM "calendar_events"`);
        await queryRunner.query(`DROP TABLE "calendar_events"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendar_events" RENAME TO "calendar_events"`);
        await queryRunner.query(`CREATE TABLE "temporary_recurring_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "recurrence_type" varchar(20) NOT NULL, "recurrence_interval" integer NOT NULL DEFAULT (1), "days_of_week" varchar(20), "day_of_month" integer, "month_of_year" integer, "recurrence_end_date" datetime, "no_end_date" boolean NOT NULL DEFAULT (0), "rrule_string" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "reminder_minutes" integer, "calendar_id" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_recurring_events"("id", "user_id", "title", "description", "color", "start_date", "end_date", "recurrence_type", "recurrence_interval", "days_of_week", "day_of_month", "month_of_year", "recurrence_end_date", "no_end_date", "rrule_string", "created_at", "updated_at", "reminder_minutes", "calendar_id") SELECT "id", "user_id", "title", "description", "color", "start_date", "end_date", "recurrence_type", "recurrence_interval", "days_of_week", "day_of_month", "month_of_year", "recurrence_end_date", "no_end_date", "rrule_string", "created_at", "updated_at", "reminder_minutes", "calendar_id" FROM "recurring_events"`);
        await queryRunner.query(`DROP TABLE "recurring_events"`);
        await queryRunner.query(`ALTER TABLE "temporary_recurring_events" RENAME TO "recurring_events"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendar_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "recurring_event_id" integer, "instance_date" date, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "is_modified" boolean DEFAULT (0), "title_override" varchar(255), "description_override" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "calendar_id" integer NOT NULL, "reminders_customized" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "temporary_calendar_events"("id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized") SELECT "id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized" FROM "calendar_events"`);
        await queryRunner.query(`DROP TABLE "calendar_events"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendar_events" RENAME TO "calendar_events"`);
        await queryRunner.query(`CREATE INDEX "IDX_b9b20fe86f496e44d479ec64c3" ON "calendars" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_06a43328baead565851e0fadbf" ON "calendar_members" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6c55288de638f693364bf00404" ON "calendar_members" ("calendar_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d485c258d7442f65c523a85dc" ON "calendar_invitations" ("invitee_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_535bd62d7dfd0bbacb97f2cd20" ON "calendar_invitations" ("calendar_id", "invitee_id") WHERE status = 'pending'`);
        await queryRunner.query(`CREATE INDEX "IDX_428d5cd1a335ab1ce207278890" ON "recurring_events" ("calendar_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ab62e63bf3615d0b9ec694b17" ON "recurrence_exceptions" ("exception_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_fea0dda27960f8e5e9abcb2c95" ON "recurrence_exceptions" ("recurring_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2ba4685cba6df66bdc080c98b" ON "calendar_events" ("calendar_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6868b6090b3268a70be9c6e61" ON "calendar_events" ("instance_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_1fb1c18e4980571fa7a88980f7" ON "calendar_events" ("recurring_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a839ac0fe4b51642c5bd993673" ON "event_reminders" ("calendar_event_id") `);
        await queryRunner.query(`DROP INDEX "IDX_0ab62e63bf3615d0b9ec694b17"`);
        await queryRunner.query(`DROP INDEX "IDX_fea0dda27960f8e5e9abcb2c95"`);
        await queryRunner.query(`CREATE TABLE "temporary_recurrence_exceptions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "recurring_event_id" integer NOT NULL, "exception_date" date NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_04aaabde0465bfc81dc47a67263" UNIQUE ("recurring_event_id", "exception_date"))`);
        await queryRunner.query(`INSERT INTO "temporary_recurrence_exceptions"("id", "recurring_event_id", "exception_date", "created_at") SELECT "id", "recurring_event_id", "exception_date", "created_at" FROM "recurrence_exceptions"`);
        await queryRunner.query(`DROP TABLE "recurrence_exceptions"`);
        await queryRunner.query(`ALTER TABLE "temporary_recurrence_exceptions" RENAME TO "recurrence_exceptions"`);
        await queryRunner.query(`CREATE INDEX "IDX_0ab62e63bf3615d0b9ec694b17" ON "recurrence_exceptions" ("exception_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_fea0dda27960f8e5e9abcb2c95" ON "recurrence_exceptions" ("recurring_event_id") `);
        await queryRunner.query(`DROP INDEX "IDX_f2ba4685cba6df66bdc080c98b"`);
        await queryRunner.query(`DROP INDEX "IDX_c6868b6090b3268a70be9c6e61"`);
        await queryRunner.query(`DROP INDEX "IDX_1fb1c18e4980571fa7a88980f7"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendar_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "recurring_event_id" integer, "instance_date" date, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "is_modified" boolean DEFAULT (0), "title_override" varchar(255), "description_override" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "calendar_id" integer NOT NULL, "reminders_customized" boolean NOT NULL DEFAULT (0), CONSTRAINT "UQ_5ec45b55e0e21281d92ddc47773" UNIQUE ("recurring_event_id", "instance_date"))`);
        await queryRunner.query(`INSERT INTO "temporary_calendar_events"("id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized") SELECT "id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized" FROM "calendar_events"`);
        await queryRunner.query(`DROP TABLE "calendar_events"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendar_events" RENAME TO "calendar_events"`);
        await queryRunner.query(`CREATE INDEX "IDX_f2ba4685cba6df66bdc080c98b" ON "calendar_events" ("calendar_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6868b6090b3268a70be9c6e61" ON "calendar_events" ("instance_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_1fb1c18e4980571fa7a88980f7" ON "calendar_events" ("recurring_event_id") `);
        await queryRunner.query(`DROP INDEX "IDX_a839ac0fe4b51642c5bd993673"`);
        await queryRunner.query(`CREATE TABLE "temporary_event_reminders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_event_id" integer NOT NULL, "reminder_minutes" integer NOT NULL, "sent_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_event_reminders_event_minutes" UNIQUE ("calendar_event_id", "reminder_minutes"))`);
        await queryRunner.query(`INSERT INTO "temporary_event_reminders"("id", "calendar_event_id", "reminder_minutes", "sent_at", "created_at", "updated_at") SELECT "id", "calendar_event_id", "reminder_minutes", "sent_at", "created_at", "updated_at" FROM "event_reminders"`);
        await queryRunner.query(`DROP TABLE "event_reminders"`);
        await queryRunner.query(`ALTER TABLE "temporary_event_reminders" RENAME TO "event_reminders"`);
        await queryRunner.query(`CREATE INDEX "IDX_a839ac0fe4b51642c5bd993673" ON "event_reminders" ("calendar_event_id") `);
        await queryRunner.query(`DROP INDEX "IDX_06a43328baead565851e0fadbf"`);
        await queryRunner.query(`DROP INDEX "IDX_6c55288de638f693364bf00404"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendar_members" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_id" integer NOT NULL, "user_id" integer NOT NULL, "role" varchar(10) NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_4b8788ccd1a51d2e877dd414239" FOREIGN KEY ("calendar_id") REFERENCES "calendars" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_06a43328baead565851e0fadbfd" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_calendar_members"("id", "calendar_id", "user_id", "role", "created_at") SELECT "id", "calendar_id", "user_id", "role", "created_at" FROM "calendar_members"`);
        await queryRunner.query(`DROP TABLE "calendar_members"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendar_members" RENAME TO "calendar_members"`);
        await queryRunner.query(`CREATE INDEX "IDX_06a43328baead565851e0fadbf" ON "calendar_members" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6c55288de638f693364bf00404" ON "calendar_members" ("calendar_id", "user_id") `);
        await queryRunner.query(`DROP INDEX "IDX_9d485c258d7442f65c523a85dc"`);
        await queryRunner.query(`DROP INDEX "IDX_535bd62d7dfd0bbacb97f2cd20"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendar_invitations" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_id" integer NOT NULL, "inviter_id" integer NOT NULL, "invitee_id" integer NOT NULL, "status" varchar(10) NOT NULL DEFAULT ('pending'), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "responded_at" datetime, CONSTRAINT "FK_a5bc8bae046772057bb52f03e27" FOREIGN KEY ("calendar_id") REFERENCES "calendars" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_2afebda9d348139d26c86216d41" FOREIGN KEY ("inviter_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_9d485c258d7442f65c523a85dc3" FOREIGN KEY ("invitee_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_calendar_invitations"("id", "calendar_id", "inviter_id", "invitee_id", "status", "created_at", "responded_at") SELECT "id", "calendar_id", "inviter_id", "invitee_id", "status", "created_at", "responded_at" FROM "calendar_invitations"`);
        await queryRunner.query(`DROP TABLE "calendar_invitations"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendar_invitations" RENAME TO "calendar_invitations"`);
        await queryRunner.query(`CREATE INDEX "IDX_9d485c258d7442f65c523a85dc" ON "calendar_invitations" ("invitee_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_535bd62d7dfd0bbacb97f2cd20" ON "calendar_invitations" ("calendar_id", "invitee_id") WHERE status = 'pending'`);
        await queryRunner.query(`DROP INDEX "IDX_0ab62e63bf3615d0b9ec694b17"`);
        await queryRunner.query(`DROP INDEX "IDX_fea0dda27960f8e5e9abcb2c95"`);
        await queryRunner.query(`CREATE TABLE "temporary_recurrence_exceptions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "recurring_event_id" integer NOT NULL, "exception_date" date NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_04aaabde0465bfc81dc47a67263" UNIQUE ("recurring_event_id", "exception_date"), CONSTRAINT "FK_fea0dda27960f8e5e9abcb2c95a" FOREIGN KEY ("recurring_event_id") REFERENCES "recurring_events" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_recurrence_exceptions"("id", "recurring_event_id", "exception_date", "created_at") SELECT "id", "recurring_event_id", "exception_date", "created_at" FROM "recurrence_exceptions"`);
        await queryRunner.query(`DROP TABLE "recurrence_exceptions"`);
        await queryRunner.query(`ALTER TABLE "temporary_recurrence_exceptions" RENAME TO "recurrence_exceptions"`);
        await queryRunner.query(`CREATE INDEX "IDX_0ab62e63bf3615d0b9ec694b17" ON "recurrence_exceptions" ("exception_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_fea0dda27960f8e5e9abcb2c95" ON "recurrence_exceptions" ("recurring_event_id") `);
        await queryRunner.query(`DROP INDEX "IDX_f2ba4685cba6df66bdc080c98b"`);
        await queryRunner.query(`DROP INDEX "IDX_c6868b6090b3268a70be9c6e61"`);
        await queryRunner.query(`DROP INDEX "IDX_1fb1c18e4980571fa7a88980f7"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendar_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "recurring_event_id" integer, "instance_date" date, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "is_modified" boolean DEFAULT (0), "title_override" varchar(255), "description_override" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "calendar_id" integer NOT NULL, "reminders_customized" boolean NOT NULL DEFAULT (0), CONSTRAINT "UQ_5ec45b55e0e21281d92ddc47773" UNIQUE ("recurring_event_id", "instance_date"), CONSTRAINT "FK_1fb1c18e4980571fa7a88980f7d" FOREIGN KEY ("recurring_event_id") REFERENCES "recurring_events" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_calendar_events"("id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized") SELECT "id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized" FROM "calendar_events"`);
        await queryRunner.query(`DROP TABLE "calendar_events"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendar_events" RENAME TO "calendar_events"`);
        await queryRunner.query(`CREATE INDEX "IDX_f2ba4685cba6df66bdc080c98b" ON "calendar_events" ("calendar_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6868b6090b3268a70be9c6e61" ON "calendar_events" ("instance_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_1fb1c18e4980571fa7a88980f7" ON "calendar_events" ("recurring_event_id") `);
        await queryRunner.query(`DROP INDEX "IDX_a839ac0fe4b51642c5bd993673"`);
        await queryRunner.query(`CREATE TABLE "temporary_event_reminders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_event_id" integer NOT NULL, "reminder_minutes" integer NOT NULL, "sent_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_event_reminders_event_minutes" UNIQUE ("calendar_event_id", "reminder_minutes"), CONSTRAINT "FK_a839ac0fe4b51642c5bd9936738" FOREIGN KEY ("calendar_event_id") REFERENCES "calendar_events" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_event_reminders"("id", "calendar_event_id", "reminder_minutes", "sent_at", "created_at", "updated_at") SELECT "id", "calendar_event_id", "reminder_minutes", "sent_at", "created_at", "updated_at" FROM "event_reminders"`);
        await queryRunner.query(`DROP TABLE "event_reminders"`);
        await queryRunner.query(`ALTER TABLE "temporary_event_reminders" RENAME TO "event_reminders"`);
        await queryRunner.query(`CREATE INDEX "IDX_a839ac0fe4b51642c5bd993673" ON "event_reminders" ("calendar_event_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_a839ac0fe4b51642c5bd993673"`);
        await queryRunner.query(`ALTER TABLE "event_reminders" RENAME TO "temporary_event_reminders"`);
        await queryRunner.query(`CREATE TABLE "event_reminders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_event_id" integer NOT NULL, "reminder_minutes" integer NOT NULL, "sent_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_event_reminders_event_minutes" UNIQUE ("calendar_event_id", "reminder_minutes"))`);
        await queryRunner.query(`INSERT INTO "event_reminders"("id", "calendar_event_id", "reminder_minutes", "sent_at", "created_at", "updated_at") SELECT "id", "calendar_event_id", "reminder_minutes", "sent_at", "created_at", "updated_at" FROM "temporary_event_reminders"`);
        await queryRunner.query(`DROP TABLE "temporary_event_reminders"`);
        await queryRunner.query(`CREATE INDEX "IDX_a839ac0fe4b51642c5bd993673" ON "event_reminders" ("calendar_event_id") `);
        await queryRunner.query(`DROP INDEX "IDX_1fb1c18e4980571fa7a88980f7"`);
        await queryRunner.query(`DROP INDEX "IDX_c6868b6090b3268a70be9c6e61"`);
        await queryRunner.query(`DROP INDEX "IDX_f2ba4685cba6df66bdc080c98b"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" RENAME TO "temporary_calendar_events"`);
        await queryRunner.query(`CREATE TABLE "calendar_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "recurring_event_id" integer, "instance_date" date, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "is_modified" boolean DEFAULT (0), "title_override" varchar(255), "description_override" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "calendar_id" integer NOT NULL, "reminders_customized" boolean NOT NULL DEFAULT (0), CONSTRAINT "UQ_5ec45b55e0e21281d92ddc47773" UNIQUE ("recurring_event_id", "instance_date"))`);
        await queryRunner.query(`INSERT INTO "calendar_events"("id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized") SELECT "id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized" FROM "temporary_calendar_events"`);
        await queryRunner.query(`DROP TABLE "temporary_calendar_events"`);
        await queryRunner.query(`CREATE INDEX "IDX_1fb1c18e4980571fa7a88980f7" ON "calendar_events" ("recurring_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6868b6090b3268a70be9c6e61" ON "calendar_events" ("instance_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2ba4685cba6df66bdc080c98b" ON "calendar_events" ("calendar_id") `);
        await queryRunner.query(`DROP INDEX "IDX_fea0dda27960f8e5e9abcb2c95"`);
        await queryRunner.query(`DROP INDEX "IDX_0ab62e63bf3615d0b9ec694b17"`);
        await queryRunner.query(`ALTER TABLE "recurrence_exceptions" RENAME TO "temporary_recurrence_exceptions"`);
        await queryRunner.query(`CREATE TABLE "recurrence_exceptions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "recurring_event_id" integer NOT NULL, "exception_date" date NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_04aaabde0465bfc81dc47a67263" UNIQUE ("recurring_event_id", "exception_date"))`);
        await queryRunner.query(`INSERT INTO "recurrence_exceptions"("id", "recurring_event_id", "exception_date", "created_at") SELECT "id", "recurring_event_id", "exception_date", "created_at" FROM "temporary_recurrence_exceptions"`);
        await queryRunner.query(`DROP TABLE "temporary_recurrence_exceptions"`);
        await queryRunner.query(`CREATE INDEX "IDX_fea0dda27960f8e5e9abcb2c95" ON "recurrence_exceptions" ("recurring_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ab62e63bf3615d0b9ec694b17" ON "recurrence_exceptions" ("exception_date") `);
        await queryRunner.query(`DROP INDEX "IDX_535bd62d7dfd0bbacb97f2cd20"`);
        await queryRunner.query(`DROP INDEX "IDX_9d485c258d7442f65c523a85dc"`);
        await queryRunner.query(`ALTER TABLE "calendar_invitations" RENAME TO "temporary_calendar_invitations"`);
        await queryRunner.query(`CREATE TABLE "calendar_invitations" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_id" integer NOT NULL, "inviter_id" integer NOT NULL, "invitee_id" integer NOT NULL, "status" varchar(10) NOT NULL DEFAULT ('pending'), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "responded_at" datetime)`);
        await queryRunner.query(`INSERT INTO "calendar_invitations"("id", "calendar_id", "inviter_id", "invitee_id", "status", "created_at", "responded_at") SELECT "id", "calendar_id", "inviter_id", "invitee_id", "status", "created_at", "responded_at" FROM "temporary_calendar_invitations"`);
        await queryRunner.query(`DROP TABLE "temporary_calendar_invitations"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_535bd62d7dfd0bbacb97f2cd20" ON "calendar_invitations" ("calendar_id", "invitee_id") WHERE status = 'pending'`);
        await queryRunner.query(`CREATE INDEX "IDX_9d485c258d7442f65c523a85dc" ON "calendar_invitations" ("invitee_id") `);
        await queryRunner.query(`DROP INDEX "IDX_6c55288de638f693364bf00404"`);
        await queryRunner.query(`DROP INDEX "IDX_06a43328baead565851e0fadbf"`);
        await queryRunner.query(`ALTER TABLE "calendar_members" RENAME TO "temporary_calendar_members"`);
        await queryRunner.query(`CREATE TABLE "calendar_members" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_id" integer NOT NULL, "user_id" integer NOT NULL, "role" varchar(10) NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "calendar_members"("id", "calendar_id", "user_id", "role", "created_at") SELECT "id", "calendar_id", "user_id", "role", "created_at" FROM "temporary_calendar_members"`);
        await queryRunner.query(`DROP TABLE "temporary_calendar_members"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6c55288de638f693364bf00404" ON "calendar_members" ("calendar_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_06a43328baead565851e0fadbf" ON "calendar_members" ("user_id") `);
        await queryRunner.query(`DROP INDEX "IDX_a839ac0fe4b51642c5bd993673"`);
        await queryRunner.query(`ALTER TABLE "event_reminders" RENAME TO "temporary_event_reminders"`);
        await queryRunner.query(`CREATE TABLE "event_reminders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_event_id" integer NOT NULL, "reminder_minutes" integer NOT NULL, "sent_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "event_reminders"("id", "calendar_event_id", "reminder_minutes", "sent_at", "created_at", "updated_at") SELECT "id", "calendar_event_id", "reminder_minutes", "sent_at", "created_at", "updated_at" FROM "temporary_event_reminders"`);
        await queryRunner.query(`DROP TABLE "temporary_event_reminders"`);
        await queryRunner.query(`CREATE INDEX "IDX_a839ac0fe4b51642c5bd993673" ON "event_reminders" ("calendar_event_id") `);
        await queryRunner.query(`DROP INDEX "IDX_1fb1c18e4980571fa7a88980f7"`);
        await queryRunner.query(`DROP INDEX "IDX_c6868b6090b3268a70be9c6e61"`);
        await queryRunner.query(`DROP INDEX "IDX_f2ba4685cba6df66bdc080c98b"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" RENAME TO "temporary_calendar_events"`);
        await queryRunner.query(`CREATE TABLE "calendar_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "recurring_event_id" integer, "instance_date" date, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "is_modified" boolean DEFAULT (0), "title_override" varchar(255), "description_override" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "calendar_id" integer NOT NULL, "reminders_customized" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "calendar_events"("id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized") SELECT "id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized" FROM "temporary_calendar_events"`);
        await queryRunner.query(`DROP TABLE "temporary_calendar_events"`);
        await queryRunner.query(`CREATE INDEX "IDX_1fb1c18e4980571fa7a88980f7" ON "calendar_events" ("recurring_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6868b6090b3268a70be9c6e61" ON "calendar_events" ("instance_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2ba4685cba6df66bdc080c98b" ON "calendar_events" ("calendar_id") `);
        await queryRunner.query(`DROP INDEX "IDX_fea0dda27960f8e5e9abcb2c95"`);
        await queryRunner.query(`DROP INDEX "IDX_0ab62e63bf3615d0b9ec694b17"`);
        await queryRunner.query(`ALTER TABLE "recurrence_exceptions" RENAME TO "temporary_recurrence_exceptions"`);
        await queryRunner.query(`CREATE TABLE "recurrence_exceptions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "recurring_event_id" integer NOT NULL, "exception_date" date NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "recurrence_exceptions"("id", "recurring_event_id", "exception_date", "created_at") SELECT "id", "recurring_event_id", "exception_date", "created_at" FROM "temporary_recurrence_exceptions"`);
        await queryRunner.query(`DROP TABLE "temporary_recurrence_exceptions"`);
        await queryRunner.query(`CREATE INDEX "IDX_fea0dda27960f8e5e9abcb2c95" ON "recurrence_exceptions" ("recurring_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ab62e63bf3615d0b9ec694b17" ON "recurrence_exceptions" ("exception_date") `);
        await queryRunner.query(`DROP INDEX "IDX_a839ac0fe4b51642c5bd993673"`);
        await queryRunner.query(`DROP INDEX "IDX_1fb1c18e4980571fa7a88980f7"`);
        await queryRunner.query(`DROP INDEX "IDX_c6868b6090b3268a70be9c6e61"`);
        await queryRunner.query(`DROP INDEX "IDX_f2ba4685cba6df66bdc080c98b"`);
        await queryRunner.query(`DROP INDEX "IDX_fea0dda27960f8e5e9abcb2c95"`);
        await queryRunner.query(`DROP INDEX "IDX_0ab62e63bf3615d0b9ec694b17"`);
        await queryRunner.query(`DROP INDEX "IDX_428d5cd1a335ab1ce207278890"`);
        await queryRunner.query(`DROP INDEX "IDX_535bd62d7dfd0bbacb97f2cd20"`);
        await queryRunner.query(`DROP INDEX "IDX_9d485c258d7442f65c523a85dc"`);
        await queryRunner.query(`DROP INDEX "IDX_6c55288de638f693364bf00404"`);
        await queryRunner.query(`DROP INDEX "IDX_06a43328baead565851e0fadbf"`);
        await queryRunner.query(`DROP INDEX "IDX_b9b20fe86f496e44d479ec64c3"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" RENAME TO "temporary_calendar_events"`);
        await queryRunner.query(`CREATE TABLE "calendar_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "recurring_event_id" integer, "instance_date" date, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "is_modified" boolean DEFAULT (0), "title_override" varchar(255), "description_override" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "calendar_id" integer, "reminders_customized" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "calendar_events"("id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized") SELECT "id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized" FROM "temporary_calendar_events"`);
        await queryRunner.query(`DROP TABLE "temporary_calendar_events"`);
        await queryRunner.query(`ALTER TABLE "recurring_events" RENAME TO "temporary_recurring_events"`);
        await queryRunner.query(`CREATE TABLE "recurring_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "recurrence_type" varchar(20) NOT NULL, "recurrence_interval" integer NOT NULL DEFAULT (1), "days_of_week" varchar(20), "day_of_month" integer, "month_of_year" integer, "recurrence_end_date" datetime, "no_end_date" boolean NOT NULL DEFAULT (0), "rrule_string" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "reminder_minutes" integer, "calendar_id" integer)`);
        await queryRunner.query(`INSERT INTO "recurring_events"("id", "user_id", "title", "description", "color", "start_date", "end_date", "recurrence_type", "recurrence_interval", "days_of_week", "day_of_month", "month_of_year", "recurrence_end_date", "no_end_date", "rrule_string", "created_at", "updated_at", "reminder_minutes", "calendar_id") SELECT "id", "user_id", "title", "description", "color", "start_date", "end_date", "recurrence_type", "recurrence_interval", "days_of_week", "day_of_month", "month_of_year", "recurrence_end_date", "no_end_date", "rrule_string", "created_at", "updated_at", "reminder_minutes", "calendar_id" FROM "temporary_recurring_events"`);
        await queryRunner.query(`DROP TABLE "temporary_recurring_events"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" RENAME TO "temporary_calendar_events"`);
        await queryRunner.query(`CREATE TABLE "calendar_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "recurring_event_id" integer, "instance_date" date, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "is_modified" boolean DEFAULT (0), "title_override" varchar(255), "description_override" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "calendar_id" integer, "reminders_customized" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "calendar_events"("id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized") SELECT "id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized" FROM "temporary_calendar_events"`);
        await queryRunner.query(`DROP TABLE "temporary_calendar_events"`);
        await queryRunner.query(`ALTER TABLE "recurring_events" RENAME TO "temporary_recurring_events"`);
        await queryRunner.query(`CREATE TABLE "recurring_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "recurrence_type" varchar(20) NOT NULL, "recurrence_interval" integer NOT NULL DEFAULT (1), "days_of_week" varchar(20), "day_of_month" integer, "month_of_year" integer, "recurrence_end_date" datetime, "no_end_date" boolean NOT NULL DEFAULT (0), "rrule_string" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "reminder_minutes" integer, "calendar_id" integer)`);
        await queryRunner.query(`INSERT INTO "recurring_events"("id", "user_id", "title", "description", "color", "start_date", "end_date", "recurrence_type", "recurrence_interval", "days_of_week", "day_of_month", "month_of_year", "recurrence_end_date", "no_end_date", "rrule_string", "created_at", "updated_at", "reminder_minutes", "calendar_id") SELECT "id", "user_id", "title", "description", "color", "start_date", "end_date", "recurrence_type", "recurrence_interval", "days_of_week", "day_of_month", "month_of_year", "recurrence_end_date", "no_end_date", "rrule_string", "created_at", "updated_at", "reminder_minutes", "calendar_id" FROM "temporary_recurring_events"`);
        await queryRunner.query(`DROP TABLE "temporary_recurring_events"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" RENAME TO "temporary_calendar_events"`);
        await queryRunner.query(`CREATE TABLE "calendar_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "recurring_event_id" integer, "instance_date" date, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "is_modified" boolean DEFAULT (0), "title_override" varchar(255), "description_override" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "calendar_id" integer, "reminders_customized" boolean NOT NULL DEFAULT (0), CONSTRAINT "UQ_calendar_events_recurring_instance" UNIQUE ("recurring_event_id", "instance_date"))`);
        await queryRunner.query(`INSERT INTO "calendar_events"("id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized") SELECT "id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized" FROM "temporary_calendar_events"`);
        await queryRunner.query(`DROP TABLE "temporary_calendar_events"`);
        await queryRunner.query(`ALTER TABLE "recurrence_exceptions" RENAME TO "temporary_recurrence_exceptions"`);
        await queryRunner.query(`CREATE TABLE "recurrence_exceptions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "recurring_event_id" integer NOT NULL, "exception_date" date NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_recurrence_exceptions_recurring_date" UNIQUE ("recurring_event_id", "exception_date"))`);
        await queryRunner.query(`INSERT INTO "recurrence_exceptions"("id", "recurring_event_id", "exception_date", "created_at") SELECT "id", "recurring_event_id", "exception_date", "created_at" FROM "temporary_recurrence_exceptions"`);
        await queryRunner.query(`DROP TABLE "temporary_recurrence_exceptions"`);
        await queryRunner.query(`ALTER TABLE "calendar_members" RENAME TO "temporary_calendar_members"`);
        await queryRunner.query(`CREATE TABLE "calendar_members" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_id" integer NOT NULL, "user_id" integer NOT NULL, "role" varchar(10) NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_calendar_members_calendar_user" UNIQUE ("calendar_id", "user_id"))`);
        await queryRunner.query(`INSERT INTO "calendar_members"("id", "calendar_id", "user_id", "role", "created_at") SELECT "id", "calendar_id", "user_id", "role", "created_at" FROM "temporary_calendar_members"`);
        await queryRunner.query(`DROP TABLE "temporary_calendar_members"`);
        await queryRunner.query(`CREATE INDEX "IDX_event_reminders_calendar_event_id" ON "event_reminders" ("calendar_event_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_event_reminders_event_minutes" ON "event_reminders" ("calendar_event_id", "reminder_minutes") `);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_events_recurring_event_id" ON "calendar_events" ("recurring_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_events_instance_date" ON "calendar_events" ("instance_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_events_calendar_id" ON "calendar_events" ("calendar_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_recurrence_exceptions_recurring_event_id" ON "recurrence_exceptions" ("recurring_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_recurrence_exceptions_exception_date" ON "recurrence_exceptions" ("exception_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_recurring_events_calendar_id" ON "recurring_events" ("calendar_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_invitations_invitee_id" ON "calendar_invitations" ("invitee_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_calendar_invitations_pending" ON "calendar_invitations" ("calendar_id", "invitee_id") WHERE "status" = 'pending'`);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_members_user_id" ON "calendar_members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_calendars_owner_id" ON "calendars" ("owner_id") `);
        await queryRunner.query(`DROP INDEX "IDX_event_reminders_calendar_event_id"`);
        await queryRunner.query(`DROP INDEX "UQ_event_reminders_event_minutes"`);
        await queryRunner.query(`ALTER TABLE "event_reminders" RENAME TO "temporary_event_reminders"`);
        await queryRunner.query(`CREATE TABLE "event_reminders" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_event_id" integer NOT NULL, "reminder_minutes" integer NOT NULL, "sent_at" datetime, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_event_reminders_calendar_event" FOREIGN KEY ("calendar_event_id") REFERENCES "calendar_events" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "event_reminders"("id", "calendar_event_id", "reminder_minutes", "sent_at", "created_at", "updated_at") SELECT "id", "calendar_event_id", "reminder_minutes", "sent_at", "created_at", "updated_at" FROM "temporary_event_reminders"`);
        await queryRunner.query(`DROP TABLE "temporary_event_reminders"`);
        await queryRunner.query(`CREATE INDEX "IDX_event_reminders_calendar_event_id" ON "event_reminders" ("calendar_event_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_event_reminders_event_minutes" ON "event_reminders" ("calendar_event_id", "reminder_minutes") `);
        await queryRunner.query(`DROP INDEX "IDX_calendar_events_recurring_event_id"`);
        await queryRunner.query(`DROP INDEX "IDX_calendar_events_instance_date"`);
        await queryRunner.query(`DROP INDEX "IDX_calendar_events_calendar_id"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" RENAME TO "temporary_calendar_events"`);
        await queryRunner.query(`CREATE TABLE "calendar_events" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "recurring_event_id" integer, "instance_date" date, "title" varchar(255) NOT NULL, "description" text, "color" varchar(20), "start_date" datetime NOT NULL, "end_date" datetime NOT NULL, "is_modified" boolean DEFAULT (0), "title_override" varchar(255), "description_override" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "calendar_id" integer, "reminders_customized" boolean NOT NULL DEFAULT (0), CONSTRAINT "UQ_calendar_events_recurring_instance" UNIQUE ("recurring_event_id", "instance_date"), CONSTRAINT "FK_calendar_events_recurring_event" FOREIGN KEY ("recurring_event_id") REFERENCES "recurring_events" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "calendar_events"("id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized") SELECT "id", "user_id", "recurring_event_id", "instance_date", "title", "description", "color", "start_date", "end_date", "is_modified", "title_override", "description_override", "created_at", "updated_at", "calendar_id", "reminders_customized" FROM "temporary_calendar_events"`);
        await queryRunner.query(`DROP TABLE "temporary_calendar_events"`);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_events_recurring_event_id" ON "calendar_events" ("recurring_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_events_instance_date" ON "calendar_events" ("instance_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_events_calendar_id" ON "calendar_events" ("calendar_id") `);
        await queryRunner.query(`DROP INDEX "IDX_recurrence_exceptions_recurring_event_id"`);
        await queryRunner.query(`DROP INDEX "IDX_recurrence_exceptions_exception_date"`);
        await queryRunner.query(`ALTER TABLE "recurrence_exceptions" RENAME TO "temporary_recurrence_exceptions"`);
        await queryRunner.query(`CREATE TABLE "recurrence_exceptions" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "recurring_event_id" integer NOT NULL, "exception_date" date NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_recurrence_exceptions_recurring_date" UNIQUE ("recurring_event_id", "exception_date"), CONSTRAINT "FK_recurrence_exceptions_recurring_event" FOREIGN KEY ("recurring_event_id") REFERENCES "recurring_events" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "recurrence_exceptions"("id", "recurring_event_id", "exception_date", "created_at") SELECT "id", "recurring_event_id", "exception_date", "created_at" FROM "temporary_recurrence_exceptions"`);
        await queryRunner.query(`DROP TABLE "temporary_recurrence_exceptions"`);
        await queryRunner.query(`CREATE INDEX "IDX_recurrence_exceptions_recurring_event_id" ON "recurrence_exceptions" ("recurring_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_recurrence_exceptions_exception_date" ON "recurrence_exceptions" ("exception_date") `);
        await queryRunner.query(`DROP INDEX "IDX_calendar_invitations_invitee_id"`);
        await queryRunner.query(`DROP INDEX "UQ_calendar_invitations_pending"`);
        await queryRunner.query(`ALTER TABLE "calendar_invitations" RENAME TO "temporary_calendar_invitations"`);
        await queryRunner.query(`CREATE TABLE "calendar_invitations" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_id" integer NOT NULL, "inviter_id" integer NOT NULL, "invitee_id" integer NOT NULL, "status" varchar(10) NOT NULL DEFAULT ('pending'), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "responded_at" datetime, CONSTRAINT "FK_calendar_invitations_invitee" FOREIGN KEY ("invitee_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_calendar_invitations_inviter" FOREIGN KEY ("inviter_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_calendar_invitations_calendar" FOREIGN KEY ("calendar_id") REFERENCES "calendars" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "calendar_invitations"("id", "calendar_id", "inviter_id", "invitee_id", "status", "created_at", "responded_at") SELECT "id", "calendar_id", "inviter_id", "invitee_id", "status", "created_at", "responded_at" FROM "temporary_calendar_invitations"`);
        await queryRunner.query(`DROP TABLE "temporary_calendar_invitations"`);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_invitations_invitee_id" ON "calendar_invitations" ("invitee_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_calendar_invitations_pending" ON "calendar_invitations" ("calendar_id", "invitee_id") WHERE "status" = 'pending'`);
        await queryRunner.query(`DROP INDEX "IDX_calendar_members_user_id"`);
        await queryRunner.query(`ALTER TABLE "calendar_members" RENAME TO "temporary_calendar_members"`);
        await queryRunner.query(`CREATE TABLE "calendar_members" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "calendar_id" integer NOT NULL, "user_id" integer NOT NULL, "role" varchar(10) NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_calendar_members_calendar_user" UNIQUE ("calendar_id", "user_id"), CONSTRAINT "FK_calendar_members_user" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_calendar_members_calendar" FOREIGN KEY ("calendar_id") REFERENCES "calendars" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "calendar_members"("id", "calendar_id", "user_id", "role", "created_at") SELECT "id", "calendar_id", "user_id", "role", "created_at" FROM "temporary_calendar_members"`);
        await queryRunner.query(`DROP TABLE "temporary_calendar_members"`);
        await queryRunner.query(`CREATE INDEX "IDX_calendar_members_user_id" ON "calendar_members" ("user_id") `);
        await queryRunner.query(`DROP INDEX "IDX_calendars_owner_id"`);
        await queryRunner.query(`ALTER TABLE "calendars" RENAME TO "temporary_calendars"`);
        await queryRunner.query(`CREATE TABLE "calendars" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(60) NOT NULL, "color" varchar(20), "owner_id" integer NOT NULL, "is_personal" boolean NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_calendars_owner" FOREIGN KEY ("owner_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "calendars"("id", "name", "color", "owner_id", "is_personal", "created_at", "updated_at") SELECT "id", "name", "color", "owner_id", "is_personal", "created_at", "updated_at" FROM "temporary_calendars"`);
        await queryRunner.query(`DROP TABLE "temporary_calendars"`);
        await queryRunner.query(`CREATE INDEX "IDX_calendars_owner_id" ON "calendars" ("owner_id") `);
    }

}
